server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: jason
    password: jason
    host: 192.168.232.128
  redis:
    host: 192.168.232.128
ly:
  sms:
    accessKeyId: LTAIZWwZTMwfbDDf # 你自己的accessKeyId
    accessKeySecret: 5VENiliqIFzzLB4qcSq8VHRGojraGL # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_165414716 # 模板名称