server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
  rabbitmq:
      host: 192.168.232.128
      username: jason
      password: jason
      virtual-host: /leyou
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 300000ms
          multiplier: 2
        exchange: ly.item.exchange
#      生产者确认
      publisher-confirms: true
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10
#  jackson:
#    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#    registry-fetch-interval-seconds: 5
  instance:
#    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
